# Generated by Django 5.0.3 on 2024-05-06 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichChiTieu',
            fields=[
                ('MaLich', models.AutoField(primary_key=True, serialize=False)),
                ('TenLich', models.CharField(max_length=100)),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
                ('NguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichchitieus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('MaLich', 'NguoiDung')},
            },
        ),
    ]
