# Generated by Django 5.0.3 on 2024-05-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lichchitieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiDungLich',
            fields=[
                ('SoThuTu', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhoanChi', models.CharField(max_length=100)),
                ('SoTienChi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LichChiTieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noidunglich', to='app.lichchitieu')),
            ],
        ),
    ]
