# Generated by Django 5.0.3 on 2024-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_noidunglich'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThuNhap',
            fields=[
                ('MaTN', models.AutoField(primary_key=True, serialize=False)),
                ('TenTN', models.CharField(max_length=100)),
                ('SoTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ngay', models.DateField()),
                ('GhiChu', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
