# Generated by Django 5.0.3 on 2024-05-06 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_thunhap_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinChiTieu',
            fields=[
                ('MaTTCT', models.AutoField(primary_key=True, serialize=False)),
                ('Ngay', models.DateField()),
                ('SoTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NoiDung', models.CharField(max_length=100)),
                ('GhiChu', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
